/*  SU Course List   */
select
    SSBSECT.SSBSECT_SUBJ_CODE,
    SSBSECT.SSBSECT_CRSE_NUMB, 
    SSBSECT.SSBSECT_SEQ_NUMB, 
    SHRTCKN.SHRTCKN_CRSE_TITLE,
    SSBSECT.SSBSECT_CAMP_CODE,
    SSBSECT.SSBSECT_REG_ONEUP,
    SSBSECT.SSBSECT_MAX_ENRL,
    SSBSECT.SSBSECT_ENRL,
    SSBSECT.SSBSECT_SEATS_AVAIL, 
    SSBSECT.SSBSECT_TOT_CREDIT_HRS,
    SSBSECT.SSBSECT_CENSUS_ENRL,
    SSBSECT.SSBSECT_GMOD_CODE g6
    --SHRTCKN.*
    --SSBSECT.SSBSECT_INSM_CODE
    --SSBSECT.SSBSECT_SURROGATE_ID
    --SSBSECT.SSBSECT_SICAS_CAMP_COURSE_ID
    
from
    SSBSECT SSBSECT

    join STVTERM STVTERM on STVTERM.STVTERM_CODE = 202240
    left outer join SHRTCKN SHRTCKN on SHRTCKN.SHRTCKN_CRN = SSBSECT.SSBSECT_CRN and SHRTCKN.SHRTCKN_TERM_CODE = 202220 and SHRTCKN.SHRTCKN_REG_SEQ = 1
where
    SSBSECT.SSBSECT_TERM_CODE = STVTERM.STVTERM_CODE
--    and SSBSECT.SSBSECT_GMOD_CODE != 'Y'
    --and SSBSECT.SSBSECT_REG_ONEUP = 1
order by
      SSBSECT.SSBSECT_SUBJ_CODE, SSBSECT.SSBSECT_CRSE_NUMB
