select 
    SPRIDEN.SPRIDEN_ID,
    SPRIDEN.SPRIDEN_LAST_NAME,
    SPRIDEN.SPRIDEN_FIRST_NAME,
    SFRSTCR_PIDM,
    SFRSTCR_TERM_CODE,
    SFRSTCR_CRN,
    SFRSTCR_REG_SEQ,
    SFRSTCR_RSTS_CODE,
    SFRSTCR_GMOD_CODE
    
from 
    SPRIDEN
    
join SFRSTCR on SFRSTCR_PIDM = SPRIDEN_PIDM

where 
     SFRSTCR_TERM_CODE = 202220
     and SFRSTCR_GMOD_CODE = 'Y'
     and SFRSTCR_RSTS_CODE in ('RE')
     and SPRIDEN_NTYP_CODE is null
     and SPRIDEN_CHANGE_IND is null
     
group by
    SPRIDEN.SPRIDEN_ID,
    SPRIDEN.SPRIDEN_LAST_NAME,
    SPRIDEN.SPRIDEN_FIRST_NAME,
    SFRSTCR_PIDM,
    SFRSTCR_TERM_CODE,
    SFRSTCR_CRN,
    SFRSTCR_REG_SEQ,
    SFRSTCR_RSTS_CODE,
    SFRSTCR_GMOD_CODE
      
order by
      SFRSTCR_CRN, SPRIDEN_LAST_NAME, SPRIDEN_FIRST_NAME