Select
    SPRIDEN.SPRIDEN_ID Banner_ID,
    CASE 
        WHEN SPBPERS.SPBPERS_SEX = 'F' THEN 'Ms.'
        WHEN SPBPERS.SPBPERS_SEX = 'M' Then 'Mr.'
        ELSE ''
        END Title,
    SPRIDEN.SPRIDEN_FIRST_NAME First_Name,
    SPRIDEN.SPRIDEN_LAST_NAME Last_Name,
    GORADID.GORADID_ADDITIONAL_ID SU_ID,        
    STVCLAS.STVCLAS_CODE Class_Code,
    STVDEGC.STVDEGC_CODE Degree_Code,
    SGBSTDN.SGBSTDN_TERM_CODE_EFF Semester,
    STVSTYP.STVSTYP_DESC Student_Type,
    STVDEPT.STVDEPT_DESC Dept_Desc,
    STVMAJR.STVMAJR_DESC Majr_Desc,

    f_format_name(SGRADVR.SGRADVR_ADVR_PIDM, 'LFMI') as Major_Prof_Advisor, 
    SHRTGPA.SHRTGPA_HOURS_ATTEMPTED Semester_HC,
    SHRTGPA.SHRTGPA_HOURS_EARNED Semester_HP,
    SHRTGPA.SHRTGPA_QUALITY_POINTS Semester_Grd_Pts,
    trunc(SHRTGPA.SHRTGPA_GPA,3) Semester_GPA,
    SHRLGPA.SHRLGPA_HOURS_ATTEMPTED Cumulative_HC,
    SHRLGPA.SHRLGPA_HOURS_EARNED Cumulative_HP,
    SHRLGPA.SHRLGPA_QUALITY_POINTS Cumulative_Grd_Pts,
    trunc(SHRLGPA.SHRLGPA_GPA,3) Cumulative_GPA,
    SPRADDR.SPRADDR_STREET_LINE1 ||' '|| SPRADDR.SPRADDR_STREET_LINE2 Permanent_Line_1,
    SPRADDR.SPRADDR_CITY ||' '|| SPRADDR.SPRADDR_STAT_CODE ||' '|| substr(SPRADDR.SPRADDR_ZIP,1,12) Permanent_Line_2,
    SPRADDR1.SPRADDR_STREET_LINE1 ||' '|| SPRADDR1.SPRADDR_STREET_LINE2 Mailing_Line_1,
    SPRADDR1.SPRADDR_CITY ||' '|| SPRADDR1.SPRADDR_STAT_CODE ||' '|| substr(SPRADDR1.SPRADDR_ZIP,1,12) Mailing_Line_2,
    GOREMAL.GOREMAL_EMAIL_ADDRESS Email


from
    SPRIDEN SPRIDEN

    join STVTERM STVTERM on STVTERM.STVTERM_CODE = 202220

    join SPBPERS SPBPERS on SPBPERS.SPBPERS_PIDM = SPRIDEN.SPRIDEN_PIDM
    
    join GOREMAL GOREMAL on GOREMAL.GOREMAL_PIDM = SPRIDEN.SPRIDEN_PIDM
        and GOREMAL.GOREMAL_PREFERRED_IND = 'Y'
        and GOREMAL.GOREMAL_EMAL_CODE = 'SU'
        and GOREMAL.GOREMAL_STATUS_IND = 'A'    

    join GORADID GORADID on GORADID.GORADID_PIDM = SPRIDEN.SPRIDEN_PIDM
         and GORADID.GORADID_ADID_CODE = 'SUID'

    join SGBSTDN SGBSTDN on SGBSTDN.SGBSTDN_PIDM = SPRIDEN.SPRIDEN_PIDM
        and SGBSTDN.SGBSTDN_TERM_CODE_EFF = fy_sgbstdn_eff_term(SGBSTDN.SGBSTDN_PIDM, STVTERM.STVTERM_CODE)
        and SGBSTDN.SGBSTDN_MAJR_CODE_1 not in ('0000', 'EHS', 'SUS', 'VIS')
        and SGBSTDN.SGBSTDN_STST_CODE in ('AS', 'IG')
        and SGBSTDN.SGBSTDN_LEVL_CODE = 'UG'

    left outer join SGRADVR SGRADVR on SGRADVR.SGRADVR_PIDM =  SPRIDEN.SPRIDEN_PIDM
        and SGRADVR.SGRADVR_ADVR_PIDM is not null

    left outer join SPRADDR SPRADDR on SPRADDR.SPRADDR_PIDM = SPRIDEN.SPRIDEN_PIDM
        and SPRADDR.SPRADDR_ATYP_CODE in ('PR')
        and SPRADDR.SPRADDR_STATUS_IND is null
        and SPRADDR_STREET_LINE1 is not null
        and SPRADDR.SPRADDR_VERSION = (
             select max(SPRADDR_VERSION)
             from SPRADDR SPRADDR1
             where SPRADDR1.SPRADDR_PIDM = SPRADDR.SPRADDR_PIDM
             and SPRADDR1.SPRADDR_ATYP_CODE in ('PR')
             and SPRADDR1.SPRADDR_STATUS_IND is null)
        and SPRADDR.SPRADDR_SURROGATE_ID = (
             select max(SPRADDR_SURROGATE_ID)
             from SPRADDR SPRADDR1
             where SPRADDR1.SPRADDR_PIDM = SPRADDR.SPRADDR_PIDM
             and SPRADDR1.SPRADDR_ATYP_CODE in ('PR')
             and SPRADDR1.SPRADDR_STATUS_IND is null)

    left outer join SPRADDR SPRADDR1 on SPRADDR1.SPRADDR_PIDM = SPRIDEN.SPRIDEN_PIDM
        and SPRADDR1.SPRADDR_ATYP_CODE in ('MA')
        and SPRADDR1.SPRADDR_STATUS_IND is null
        and SPRADDR1.SPRADDR_STREET_LINE1 is not null
        and SPRADDR1.SPRADDR_VERSION = (
             select max(SPRADDR_VERSION)
             from SPRADDR SPRADDR2
             where SPRADDR2.SPRADDR_PIDM = SPRADDR1.SPRADDR_PIDM
             and SPRADDR2.SPRADDR_ATYP_CODE in ('MA')
             and SPRADDR2.SPRADDR_STATUS_IND is null)
        and SPRADDR1.SPRADDR_SURROGATE_ID = (
             select max(SPRADDR_SURROGATE_ID)
             from SPRADDR SPRADDR2
             where SPRADDR2.SPRADDR_PIDM = SPRADDR1.SPRADDR_PIDM
             and SPRADDR2.SPRADDR_ATYP_CODE in ('MA')
             and SPRADDR2.SPRADDR_STATUS_IND is null)

    left outer join SHRTGPA SHRTGPA on SHRTGPA.SHRTGPA_PIDM = SPRIDEN.SPRIDEN_PIDM
        and SHRTGPA.SHRTGPA_TERM_CODE = STVTERM.STVTERM_CODE
        and SHRTGPA.SHRTGPA_GPA_TYPE_IND = 'I'

    left outer join SHRLGPA SHRLGPA on SHRLGPA.SHRLGPA_PIDM = SPRIDEN.SPRIDEN_PIDM
         and SHRLGPA.SHRLGPA_LEVL_CODE = SGBSTDN.SGBSTDN_LEVL_CODE
         and SHRLGPA.SHRLGPA_GPA_TYPE_IND = 'O'
         and SHRLGPA.SHRLGPA_GPA is not null             

    left outer join STVCLAS STVCLAS on STVCLAS.STVCLAS_CODE = f_class_calc_fnc(SGBSTDN.SGBSTDN_PIDM,SGBSTDN.SGBSTDN_LEVL_CODE, STVTERM.STVTERM_CODE)

    left outer join STVDEPT STVDEPT on STVDEPT.STVDEPT_CODE = SGBSTDN.SGBSTDN_DEPT_CODE

    left outer join STVDEGC STVDEGC on STVDEGC.STVDEGC_CODE = SGBSTDN.SGBSTDN_DEGC_CODE_1
    
    left outer join STVMAJR STVMAJR on STVMAJR.STVMAJR_CODE = SGBSTDN.SGBSTDN_MAJR_CODE_1
    
    join STVSTYP STVSTYP on STVSTYP.STVSTYP_CODE = SGBSTDN.SGBSTDN_STYP_CODE


where
    SPRIDEN.SPRIDEN_NTYP_CODE is null
    and SPRIDEN.SPRIDEN_CHANGE_IND is null
    and SGRADVR.SGRADVR_ADVR_PIDM is not null
    and SGRADVR.SGRADVR_PRIM_IND = 'Y'
    and (
        -- main campus standards
        ((
         SHRLGPA.SHRLGPA_HOURS_EARNED < 30.0
         and SHRLGPA.SHRLGPA_GPA < 1.7000000
        )
        or(
        SHRLGPA.SHRLGPA_HOURS_EARNED >= 30.0
        and SHRLGPA.SHRLGPA_HOURS_EARNED < 60.0
        and SHRLGPA.SHRLGPA_GPA < 1.850
        )
        or(
        SHRLGPA.SHRLGPA_HOURS_EARNED >= 60.0
        and SHRLGPA.SHRLGPA_GPA < 2.000
        )
            )
            -- ranger schools standards
            or (SHRLGPA.SHRLGPA_GPA < 2.000 
            and((stvterm_code like '%%%%10') 
            or (stvterm_code like '%%%%30'))
       ))
    and exists(
        select *
        from SFRSTCR SFRSTCR
        where SFRSTCR.SFRSTCR_PIDM = SPRIDEN.SPRIDEN_PIDM
        and SFRSTCR.SFRSTCR_TERM_CODE = STVTERM.STVTERM_CODE
    )
order by
        STVCLAS.STVCLAS_SURROGATE_ID, SPRIDEN.SPRIDEN_SEARCH_LAST_NAME
