/* SAP Final Protoype */

select    
    SPRIDEN.SPRIDEN_ID Banner_ID,
    SPRIDEN.SPRIDEN_LAST_NAME Last_Name,
    SPRIDEN.SPRIDEN_FIRST_NAME First_Name,
    GORADID.GORADID_ADDITIONAL_ID SUID,
    SGBSTDN.SGBSTDN_LEVL_CODE Student_Level,
    STVCLAS.STVCLAS_DESC Studnt_Class_Level,  
    STVMAJR.STVMAJR_DESC Program_Of_Study,  
    SHRTTRM.SHRTTRM_TERM_CODE SAP_TERM_CODE,
    SHRTTRM.SHRTTRM_ASTD_CODE_END_OF_TERM SAP_CODE,
    SHRTTRM.SHRTTRM_ASTD_DATE_END_OF_TERM SAP_CHANGE_DATE,
    CASE 
    WHEN EXISTS(SELECT 1 FROM RPRATRM RPRATRM WHERE RPRATRM.RPRATRM_PIDM = SPRIDEN.SPRIDEN_PIDM
      AND RPRATRM.RPRATRM_TERM_CODE = STVTERM_CODE AND RPRATRM.RPRATRM_FUND_CODE IN ('FSUB', 'FUSB', 'FPLS', 'FPELL', 'FFWS', 'FSEOG', 'FGPLS')
      AND RPRATRM.RPRATRM_AWST_CODE IN ( 'A', 'WA', 'MA')) THEN 'Y'
    ELSE 'N'
    END ACCEPTED_AID,
    --SGBSTDN.SGBSTDN_TERM_CODE_EFF Semester,
    SHRTGPA.SHRTGPA_HOURS_ATTEMPTED Semester_HC,
    SHRTGPA.SHRTGPA_GPA_HOURS Semester_HP,
    SHRTGPA.SHRTGPA_QUALITY_POINTS Semester_Grd_Pts,
    trunc(SHRTGPA.SHRTGPA_GPA,3) Semester_GPA,    
    SHRLGPA.SHRLGPA_HOURS_ATTEMPTED Cum_HC,
    SHRLGPA.SHRLGPA_GPA_HOURS Cum_HP,
    SHRLGPA.SHRLGPA_QUALITY_POINTS Cum_Grd_Pts,
    trunc(SHRLGPA.SHRLGPA_GPA,3) Cum_GPA,
    SPRADDR.SPRADDR_STREET_LINE1 Street_1,
    SPRADDR.SPRADDR_STREET_LINE2 Street_2,
    SPRADDR.SPRADDR_CITY City,
    SPRADDR.SPRADDR_STAT_CODE State,
    substr(SPRADDR.SPRADDR_ZIP,1,5) Zip_Code,
    GOREMAL.GOREMAL_EMAIL_ADDRESS Email_Address,
    GOREMAL2.GOREMAL_EMAIL_ADDRESS Per_Email_Address
        
from
    SPRIDEN SPRIDEN

    join STVTERM STVTERM on STVTERM.STVTERM_CODE = 202220
    
    join GORADID GORADID on GORADID.GORADID_PIDM = SPRIDEN.SPRIDEN_PIDM
         and GORADID.GORADID_ADID_CODE = 'SUID'    

    join GOREMAL GOREMAL on GOREMAL.GOREMAL_PIDM = SPRIDEN.SPRIDEN_PIDM
        and GOREMAL.GOREMAL_PREFERRED_IND = 'Y'
        and GOREMAL.GOREMAL_EMAL_CODE = 'SU'
        and GOREMAL.GOREMAL_STATUS_IND = 'A'
    
    left outer join GOREMAL GOREMAL2 on GOREMAL2.GOREMAL_PIDM = SPRIDEN.SPRIDEN_PIDM
        and GOREMAL2.GOREMAL_EMAL_CODE = 'PERS'
        and GOREMAL2.GOREMAL_STATUS_IND = 'A'
        
    join SGBSTDN SGBSTDN on SGBSTDN.SGBSTDN_PIDM = SPRIDEN.SPRIDEN_PIDM
         and SGBSTDN.SGBSTDN_TERM_CODE_EFF = fy_sgbstdn_eff_term(SGBSTDN.SGBSTDN_PIDM, STVTERM.STVTERM_CODE)
         and SGBSTDN.SGBSTDN_MAJR_CODE_1 not in ('0000', 'EHS', 'SUS', 'VIS')
         and SGBSTDN.SGBSTDN_STST_CODE = 'AS'
    
    left outer join SHRTGPA SHRTGPA on SHRTGPA.SHRTGPA_PIDM = SPRIDEN.SPRIDEN_PIDM
         and SHRTGPA_TERM_CODE = STVTERM.STVTERM_CODE
         and SHRTGPA.SHRTGPA_GPA_TYPE_IND = 'I' 
    
    left outer join SHRLGPA SHRLGPA on SHRLGPA.SHRLGPA_PIDM = SPRIDEN.SPRIDEN_PIDM
         and SHRLGPA.SHRLGPA_LEVL_CODE = SGBSTDN.SGBSTDN_LEVL_CODE
         and SHRLGPA.SHRLGPA_GPA_TYPE_IND = 'I'
         and SHRLGPA.SHRLGPA_GPA is not null         

    left outer join SPRADDR SPRADDR on SPRADDR.SPRADDR_PIDM = SPRIDEN.SPRIDEN_PIDM
         and SPRADDR.SPRADDR_ATYP_CODE in ('PR')
         and SPRADDR.SPRADDR_STATUS_IND is null
         and SPRADDR.SPRADDR_VERSION = (
             select max(SPRADDR_VERSION)
             from SPRADDR SPRADDR1
             where SPRADDR1.SPRADDR_PIDM = SPRADDR.SPRADDR_PIDM
             and SPRADDR1.SPRADDR_ATYP_CODE in ('PR')
             and SPRADDR1.SPRADDR_STATUS_IND is null)
        and SPRADDR.SPRADDR_SURROGATE_ID = (
             select max(SPRADDR_SURROGATE_ID)
             from SPRADDR SPRADDR1
             where SPRADDR1.SPRADDR_PIDM = SPRADDR.SPRADDR_PIDM
             and SPRADDR1.SPRADDR_ATYP_CODE in ('PR')
             and SPRADDR1.SPRADDR_STATUS_IND is null)

    left outer join SHRTTRM SHRTTRM on SHRTTRM.SHRTTRM_PIDM = SPRIDEN.SPRIDEN_PIDM
         and SHRTTRM.SHRTTRM_TERM_CODE = STVTERM.STVTERM_CODE
         
    left outer join STVCLAS STVCLAS on STVCLAS.STVCLAS_CODE = f_class_calc_fnc(SGBSTDN.SGBSTDN_PIDM,SGBSTDN.SGBSTDN_LEVL_CODE, STVTERM.STVTERM_CODE)

    left outer join STVDEPT STVDEPT on STVDEPT.STVDEPT_CODE = SGBSTDN.SGBSTDN_DEPT_CODE

    left outer join STVDEGC STVDEGC on STVDEGC.STVDEGC_CODE = SGBSTDN.SGBSTDN_DEGC_CODE_1

    left outer join STVMAJR STVMAJR on STVMAJR.STVMAJR_CODE = SGBSTDN.SGBSTDN_MAJR_CODE_1

    join STVSTYP STVSTYP on STVSTYP.STVSTYP_CODE = SGBSTDN.SGBSTDN_STYP_CODE        
                     
where 
      SPRIDEN.SPRIDEN_NTYP_CODE is null 
      and SPRIDEN.SPRIDEN_CHANGE_IND is null   
      and exists( select * from SFRSTCR where SFRSTCR_PIDM = SPRIDEN_PIDM and SFRSTCR_TERM_CODE = STVTERM.STVTERM_CODE and SFRSTCR_RSTS_CODE = 'RE')
    
order by 
      SPRIDEN.SPRIDEN_LAST_NAME
