--select * from rel_course_Attributes
--select * from AGG_COURSE_ATTRIBUTES
--select * from REL_COURSE_SECTIONS
--select * from AGG_COURSE_SECTIONS
select 

SSBSECT.SSBSECT_CRN CRN, 
SSBSECT.SSBSECT_SUBJ_CODE ||' ' ||
SSBSECT.SSBSECT_CRSE_NUMB Course,
SSBSECT.SSBSECT_SEQ_NUMB Seq_NO,
SSBSECT.SSBSECT_TERM_CODE,
a.AGG_ATTR_DESC


from SSBSECT SSBSECT

join AGG_COURSE_ATTRIBUTES a  on SSBSECT.SSBSECT_CRN = a.CRN and a.TERM_CODE = SSBSECT.SSBSECT_TERM_CODE
--join REL_COURSE_ATTRIBUTES r  on SSBSECT.SSBSECT_CRN = r.CRN and r.TERM_CODE = SSBSECT.SSBSECT_TERM_CODE
where SSBSECT.SSBSECT_TERM_CODE = 202240
      and SSBSECT.SSBSECT_GMOD_CODE = 'Y'
order by  SSBSECT.SSBSECT_SUBJ_CODE, SSBSECT.SSBSECT_CRSE_NUMB, SSBSECT.SSBSECT_SEQ_NUMB
