select
    SPRIDEN.SPRIDEN_ID Banner_ID,
    SPRIDEN.SPRIDEN_LAST_NAME Last_Name,
    SPRIDEN.SPRIDEN_FIRST_NAME First_Name,
    STVCLAS.STVCLAS_DESC Student_Class,
    STVMAJR.STVMAJR_DESC Program_of_Study,
    STVDEGC.STVDEGC_CODE Degree_Program,
    SGBSTDN.SGBSTDN_STYP_CODE Reg_Type,
    SGBSTDN.SGBSTDN_STST_CODE STST_CODE,
    SPRHOLD.SPRHOLD_HLDD_CODE Hold_Code,
    STVHLDD.STVHLDD_DESC Hold_Desc,
    SPRHOLD.SPRHOLD_FROM_DATE From_Date,
    SPRHOLD.SPRHOLD_TO_DATE To_Date,
    SPRHOLD.SPRHOLD_REASON Hold_Reason,
    SPRHOLD.SPRHOLD_AMOUNT_OWED Hold_Amount

from
    SPRIDEN SPRIDEN

    join STVTERM STVTERM on STVTERM.STVTERM_CODE = :ListBox1.STVTERM_CODE

    join GORADID GORADID on GORADID.GORADID_PIDM = SPRIDEN.SPRIDEN_PIDM
        and GORADID.GORADID_ADID_CODE = 'SUID'

    join SGBSTDN SGBSTDN on SGBSTDN.SGBSTDN_PIDM = SPRIDEN.SPRIDEN_PIDM
        and SGBSTDN.SGBSTDN_TERM_CODE_EFF = fy_sgbstdn_eff_term(SGBSTDN.SGBSTDN_PIDM, STVTERM.STVTERM_CODE)
        and SGBSTDN.SGBSTDN_MAJR_CODE_1 not in ('0000', 'EHS', 'SUS', 'VIS')
        and SGBSTDN.SGBSTDN_STST_CODE = :DropDown1.STVSTST_CODE
        and SGBSTDN.SGBSTDN_LEVL_CODE = :DropDown2.STVLEVL_CODE

    join STVMAJR STVMAJR on STVMAJR.STVMAJR_CODE = SGBSTDN.SGBSTDN_MAJR_CODE_1

    join STVDEGC STVDEGC on STVDEGC.STVDEGC_CODE = SGBSTDN.SGBSTDN_DEGC_CODE_1

    join STVCLAS STVCLAS on STVCLAS.STVCLAS_CODE = f_class_calc_fnc(SGBSTDN.SGBSTDN_PIDM,SGBSTDN.SGBSTDN_LEVL_CODE, SGBSTDN.SGBSTDN_TERM_CODE_EFF)

    join SPRHOLD SPRHOLD on SPRHOLD.SPRHOLD_PIDM = SPRIDEN.SPRIDEN_PIDM
         and SPRHOLD_FROM_DATE >= to_date(STVTERM.STVTERM_START_DATE)

    join STVHLDD STVHLDD on STVHLDD.STVHLDD_CODE = SPRHOLD.SPRHOLD_HLDD_CODE

where
    SPRIDEN.SPRIDEN_NTYP_CODE is null
    and SPRIDEN.SPRIDEN_CHANGE_IND is null
--$addfilter

--$beginorder

order by
    SPRIDEN.SPRIDEN_LAST_NAME, SPRIDEN.SPRIDEN_FIRST_NAME

--$endorder