/* 

Logical sources

select * from SSBSECT where SSBSECT_SUBJ_CODE = 'PHY'
select * from SHRTCKN
select * from sfrstcr
--SFRSTCR crn, 
--SSASECT - b
--shrtckn coll_code

*/
Select
    SPRIDEN.SPRIDEN_ID Banner_ID,
    SPRIDEN.SPRIDEN_LAST_NAME Last_Name,
    SPRIDEN.SPRIDEN_FIRST_NAME First_Name,
    GORADID.GORADID_ADDITIONAL_ID SUid,
   
    STVDEPT.STVDEPT_CODE Department,
    STVMAJR.STVMAJR_CODE Major_Program,
    STVCLAS.STVCLAS_CODE Student_Class
    --course code
    --course crn
    --course credit hour totals
    

from
    SPRIDEN SPRIDEN

    join STVTERM STVTERM on STVTERM.STVTERM_CODE = 202220

    join SGBSTDN SGBSTDN on SGBSTDN.SGBSTDN_PIDM = SPRIDEN.SPRIDEN_PIDM
         and SGBSTDN.SGBSTDN_TERM_CODE_EFF = fy_sgbstdn_eff_term(SGBSTDN.SGBSTDN_PIDM, STVTERM.STVTERM_CODE)
         and SGBSTDN.SGBSTDN_MAJR_CODE_1 not in ('0000', 'EHS', 'SUS', 'VIS')
         and SGBSTDN.SGBSTDN_STST_CODE = 'AS'--:DropDown2.STVSTST_CODE
         and SGBSTDN.SGBSTDN_LEVL_CODE = 'UG'--:DropDown3.STVLEVL_CODE
    
    join STVTERM STVTERM on STVTERM.STVTERM_CODE = 202220--:DropDown1.STVTERM_CODE

    join SPBPERS SPBPERS on SPBPERS.SPBPERS_PIDM = SPRIDEN.SPRIDEN_PIDM

    join GORADID GORADID on GORADID.GORADID_PIDM = SPRIDEN.SPRIDEN_PIDM
         and GORADID.GORADID_ADID_CODE = 'SUID'

    join GOREMAL GOREMAL on GOREMAL.GOREMAL_PIDM = SPRIDEN.SPRIDEN_PIDM
         and GOREMAL.GOREMAL_PREFERRED_IND = 'Y'
         and GOREMAL.GOREMAL_EMAL_CODE = 'SU'

    left outer join STVDEGC STVDEGC on STVDEGC.STVDEGC_CODE = SGBSTDN.SGBSTDN_DEGC_CODE_1

    left outer join STVMAJR STVMAJR on STVMAJR.STVMAJR_CODE = SGBSTDN.SGBSTDN_MAJR_CODE_1

    left outer join STVDEPT STVDEPT on STVDEPT.STVDEPT_CODE = SGBSTDN.SGBSTDN_DEPT_CODE

    left outer join STVCLAS STVCLAS on STVCLAS.STVCLAS_CODE = f_class_calc_fnc(SGBSTDN.SGBSTDN_PIDM,SGBSTDN.SGBSTDN_LEVL_CODE, STVTERM.STVTERM_CODE)


where
    SPRIDEN.SPRIDEN_NTYP_CODE is null
    and SPRIDEN.SPRIDEN_CHANGE_IND is null
    and exists(
        select * from SFRSTCR SFRSTCR
        where SFRSTCR.SFRSTCR_PIDM = SPRIDEN.SPRIDEN_PIDM
              and SFRSTCR.SFRSTCR_RSTS_CODE in ('RE','RW'))
              
    and exists(
        select * from SHRTCKN x
        where x.SHRTCKN_TERM_CODE = STVTERM.STVTERM_CODE
        and x.SHRTCKN_COLL_CODE = 'SU'
        and x.SHRTCKN_PIDM = SPRIDEN.SPRIDEN_PIDM
    
    )
              
group by
    SPRIDEN.SPRIDEN_ID,
    SPRIDEN.SPRIDEN_LAST_NAME,
    SPRIDEN.SPRIDEN_FIRST_NAME,
    GORADID.GORADID_ADDITIONAL_ID,
    STVCLAS.STVCLAS_CODE ,
    STVDEPT.STVDEPT_CODE,
    STVMAJR.STVMAJR_CODE
    
order by 
      STVDEPT.STVDEPT_CODE, 
      STVMAJR.STVMAJR_CODE, 
      STVCLAS.STVCLAS_CODE, 
      SPRIDEN.SPRIDEN_LAST_NAME, 
      SPRIDEN.SPRIDEN_FIRST_NAME
