select stvclas_code, sfrstcr.*, ssbsect.* from SFRSTCR

left outer join SSBSECT SSBSECT on SSBSECT.SSBSECT_CRN = SFRSTCR_CRN and SSBSECT_TERM_CODE = SFRSTCR_TERM_CODE
left outer join STVCLAS STVCLAS on STVCLAS.STVCLAS_CODE = f_class_calc_fnc(SFRSTCR.SFRSTCR_PIDM,SFRSTCR.SFRSTCR_LEVL_CODE, SFRSTCR_TERM_CODE)
left outer join SGBSTDN SGBSTDN on SGBSTDN.SGBSTDN_PIDM = SFRSTCR_PIDM and SGBSTDN.SGBSTDN_TERM_CODE_EFF = 202220
     and SGBSTDN_MAJR_CODE_1 not in ('0000', 'EHS', 'SUS', 'VIS', 'UNDC')
where sfrstcr_gmod_code = 'Y'
and SFRSTCR_RSTS_CODE = 'RE'
and SFRSTCR_TERM_CODE = 202220
and SSBSECT_TOT_CREDIT_HRS > 0
order by SSBSECT_SUBJ_CODE, SSBSECT_CRSE_NUMB
