Select
      SARADAP.SARADAP_TERM_CODE_ENTRY Term_Code,
      SARADAP.SARADAP_APPL_NO Appl_Num,
      SARADAP.SARADAP_APPL_DATE Appl_Date,
      SPRIDEN.SPRIDEN_ID Banner_ID,
      SPRIDEN.SPRIDEN_LAST_NAME Last_Name,
      SPRIDEN.SPRIDEN_FIRST_NAME First_Name,
      SPRIDEN.SPRIDEN_MI MI,
      f_format_name(SPRIDEN_PIDM, 'LFMI') Full_Name,
      f_get_desc_fnc('STVAPST',SARADAP.SARADAP_APST_CODE, 30) Status_Desc,
      SARADAP.SARADAP_ADMT_CODE Admission_Code,
      f_get_desc_fnc('STVADMT',SARADAP.SARADAP_ADMT_CODE,30) Admission_Desc,
      SARADAP.SARADAP_STYP_CODE STYP_Code,
      f_get_desc_fnc('STVCAMP',SARADAP.SARADAP_CAMP_CODE,30 ) Campus_Desc,
      f_get_desc_fnc('STVCOLL',SARADAP.SARADAP_COLL_CODE_1,30 ) College_Desc,
      f_get_desc_fnc('STVDEGC',SARADAP.SARADAP_DEGC_CODE_1,30 ) Degree_Desc,
      f_get_desc_fnc('STVMAJR',SARADAP.SARADAP_MAJR_CODE_1,30 ) Major_Desc,
      f_get_desc_fnc('STVMAJR',SARADAP.SARADAP_MAJR_CODE_CONC_1,30 ) Conc_Desc,
      f_get_desc_fnc('STVMAJR',SARADAP.SARADAP_DEPT_CODE,30 ) Dept_Desc

from
    SPRIDEN SPRIDEN

    join STVTERM STVTERM on STVTERM.STVTERM_CODE = :ListBox1.STVTERM_CODE

    join SPBPERS SPBPERS on SPBPERS.SPBPERS_PIDM = SPRIDEN.SPRIDEN_PIDM

    join SGBSTDN SGBSTDN on SGBSTDN.SGBSTDN_PIDM = SPRIDEN.SPRIDEN_PIDM
         and SGBSTDN.SGBSTDN_TERM_CODE_EFF = fy_sgbstdn_eff_term(SGBSTDN.SGBSTDN_PIDM, STVTERM.STVTERM_CODE)
         and SGBSTDN.SGBSTDN_MAJR_CODE_1 not in ('0000', 'EHS', 'SUS', 'VIS')
         and SGBSTDN.SGBSTDN_LEVL_CODE = 'GR'
    and SGBSTDN.SGBSTDN_STYP_CODE in ('R', 'N', 'G', 'D', 'X')

    join GOREMAL GOREMAL on GOREMAL.GOREMAL_PIDM = SPRIDEN.SPRIDEN_PIDM
        and GOREMAL.GOREMAL_PREFERRED_IND = 'Y'
        and GOREMAL.GOREMAL_EMAL_CODE = 'SU'
        and GOREMAL.GOREMAL_STATUS_IND = 'A'

    join GORADID GORADID on GORADID.GORADID_PIDM = SPRIDEN.SPRIDEN_PIDM
        and GORADID.GORADID_ADID_CODE = 'SUID'

    left outer join SARADAP SARADAP on SARADAP.SARADAP_PIDM = SPRIDEN.SPRIDEN_PIDM
        and SARADAP.SARADAP_TERM_CODE_ENTRY = STVTERM.STVTERM_CODE
where
    SPRIDEN.SPRIDEN_NTYP_CODE is null
    and SPRIDEN.SPRIDEN_CHANGE_IND is null

--$addfilter

order by
    SPRIDEN.SPRIDEN_SEARCH_LAST_NAME