Select
    SPRIDEN.SPRIDEN_ID Banner_ID,
    SPRIDEN.SPRIDEN_LAST_NAME Last_Name,
    SPRIDEN.SPRIDEN_FIRST_NAME First_Name,
    f_format_name(SPRIDEN_PIDM, 'LFMI') Full_Name,
    SHRDGMR.SHRDGMR_LEVL_CODE Student_Level,
    STVCLAS.STVCLAS_DESC Student_Class,
    STVDEGC.STVDEGC_CODE Degree_Program,
    STVMAJR.STVMAJR_DESC Major_Program,
    STVMAJR2.STVMAJR_DESC Minor_Program,
    STVMAJR3.STVMAJR_DESC Conc_Program,
    case
      when ((SHRLGPA.SHRLGPA_GPA > 3.0) and (SHRLGPA.SHRLGPA_GPA < 3.333)) then 'Cum Laude'
      when ((SHRLGPA.SHRLGPA_GPA > 3.334) and (SHRLGPA.SHRLGPA_GPA < 3.829)) then 'Magna Cum Laude'
      when ((SHRLGPA.SHRLGPA_GPA > 3.830)) then 'Summa Cum Laude'
        else ''
    end Superlatives,
    case
         when SHRTTRM.SHRTTRM_ASTD_CODE_DL in ('PR','PL') then 'Presidents List'
         when SHRTTRM.SHRTTRM_ASTD_CODE_DL = 'DL' then 'Deans List'
           else ''
    end as Deans_List,
    case
        when SGRSATT.SGRSATT_ATTS_CODE in ('LHON','UHON', 'HONR') then 'Y'
        else 'N'
    end Honors,
    SHRDGMR.SHRDGMR_GRAD_DATE Grad_Date,
    GOREMAL.GOREMAL_EMAIL_ADDRESS Email_Address

from
    SPRIDEN SPRIDEN

    join STVTERM STVTERM on STVTERM.STVTERM_CODE = :parm_term_code_select.STVTERM_CODE

    join SPBPERS SPBPERS on SPBPERS.SPBPERS_pidm = SPRIDEN.SPRIDEN_PIDM

    join GOREMAL GOREMAL on GOREMAL.GOREMAL_PIDM = SPRIDEN.SPRIDEN_PIDM
        and GOREMAL.GOREMAL_PREFERRED_IND = 'Y'
        and GOREMAL.GOREMAL_EMAL_CODE = 'SU'
        and GOREMAL.GOREMAL_STATUS_IND = 'A'

    join SHRDGMR SHRDGMR on SHRDGMR.SHRDGMR_PIDM = SPRIDEN.SPRIDEN_PIDM
        and SHRDGMR.SHRDGMR_TERM_CODE_GRAD = STVTERM.STVTERM_CODE
        and SHRDGMR.SHRDGMR_DEGS_CODE = 'GR'

    left outer join SHRTTRM SHRTTRM on SHRTTRM.SHRTTRM_PIDM = SPRIDEN.SPRIDEN_PIDM
        and SHRTTRM.SHRTTRM_TERM_CODE = (
            select max(SHRTTRM_TERM_CODE)
            from SHRTTRM SHRTTRM2
            where SHRTTRM2.SHRTTRM_PIDM = SPRIDEN.SPRIDEN_PIDM)

    left outer join SGRSATT SGRSATT on SGRSATT.SGRSATT_PIDM = SPRIDEN.SPRIDEN_PIDM
        and SGRSATT.SGRSATT_TERM_CODE_EFF = STVTERM.STVTERM_CODE
        and SGRSATT.SGRSATT_ATTS_CODE in ('HONR','UHON')

    left outer join SHRLGPA SHRLGPA on SHRLGPA.SHRLGPA_PIDM = SPRIDEN.SPRIDEN_PIDM
        and SHRLGPA.SHRLGPA_GPA_TYPE_IND = 'I'
        and SHRLGPA.SHRLGPA_LEVL_CODE = SHRDGMR.SHRDGMR_LEVL_CODE

    left outer join STVCLAS STVCLAS on STVCLAS.STVCLAS_CODE = f_class_calc_fnc(SHRDGMR.SHRDGMR_PIDM,SHRDGMR.SHRDGMR_LEVL_CODE, STVTERM.STVTERM_CODE)
    left outer join STVDEGC STVDEGC on STVDEGC.STVDEGC_CODE = SHRDGMR.SHRDGMR_DEGC_CODE
    left outer join STVMAJR STVMAJR on STVMAJR.STVMAJR_CODE = SHRDGMR.SHRDGMR_MAJR_CODE_1
    left outer join STVMAJR STVMAJR2 on STVMAJR2.STVMAJR_CODE = SHRDGMR.SHRDGMR_MAJR_CODE_MINR_1
    left outer join STVMAJR STVMAJR3 on STVMAJR3.STVMAJR_CODE = SHRDGMR.SHRDGMR_MAJR_CODE_CONC_1

where
    SPRIDEN.SPRIDEN_NTYP_CODE is null
    and SPRIDEN.SPRIDEN_CHANGE_IND is null

--$addfilter

--$beginorder

order by
      SPRIDEN.SPRIDEN_SEARCH_LAST_NAME, SPRIDEN.SPRIDEN_FIRST_NAME

--$endorder
